### ISSUE TITLE
Add the unit tests with PHPUnit

### ISSUE THREAD

**Issue by peter279k** [ingenerator/tokenista#4]
As title, if possible, can I help this issue?
I can send the PR for this.

Thanks.

**Comment by acoulton** [comment]
@peter279k I assume you've seen there are phpspec specs at the moment?

We are gradually moving away from phpspec as a company, so if you'd like to rewrite them in phpunit as a PR please do. You will obviously need to make sure you at least cover all the same things that the specs currently test.
